apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apigee-openshift-scc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  project: apigee-hybrid
  source:
    repoURL: https://github.com/smaddula862/kong.git
    targetRevision: claude/apigee-hybrid-openshift-argocd-m1kdih
    path: apigee-hybrid-gitops/base/scc
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
